# Copyright (c) 2025 Bytedance Ltd. and/or its affiliates
# SPDX-License-Identifier: MIT

from typing import List, Dict, Any, TypedDict, Optional
from pydantic import BaseModel, Field
import uuid
from langgraph.graph import MessagesState

from src.prompts.planner_model import Plan


class SearchResult(TypedDict):
    """Represents a single search result item."""
    id: str  # Unique identifier for the search result
    title: str  # Title of the search result
    url: str  # URL of the search result
    content: str  # Content snippet of the search result
    relevance_score: float  # Relevance score of the search result
    raw: Dict[str, Any]  # Raw data from the search result source
    metadata: Dict[str, Any]  # Additional metadata associated with the search result


class Observation(TypedDict):
    """
    Represents a piece of information or a summary of findings collected during 
    the research process. This can be a direct result from a tool or a 
    consolidated summary from a subgraph like the ResearchTeamSubgraph.
    """
    id: str  # Identifier of task
    title: str    # A concise title for the observation or finding.
    content: str  # The detailed content of the observation or summary.
    source: str   # Origin of the observation


class State(MessagesState):
    """
    Represents the overall state of the main agentic workflow. 
    It manages the flow of information, plans, observations, and intermediate results 
    throughout the entire research process, including interactions with subgraphs.
    
    Note: Default values for fields must be handled during state initialization 
    or by the logic within graph nodes, as TypedDicts do not inherently support
    Pydantic-style default_factory or default values in field definitions.
    """
    # Runtime Variables
    # The user's detected language locale (e.g., en-US, zh-CN). Typically defaults to "en-US".
    locale: str 
    # List of research observations collected during workflow execution. Initializes to an empty list.
    observations: List[Observation]
    # Counter for the number of planning cycles performed. Initializes to 0.
    plan_iterations: int
    # The current research plan, either as a Plan object or JSON string. Can be None initially.
    current_plan: Optional[Plan | str]
    # The generated final research report. Initializes to an empty string.
    final_report: str
    # Flag to automatically accept plans without human feedback. Typically, defaults to False.
    auto_accepted_plan: bool
    # Flag to enable preliminary search before planning. Typically, defaults to True.
    enable_background_investigation: bool
    # Results from the background investigation node. Can be None initially.
    background_investigation_results: Optional[str]

    # New field to track the current step from the main plan being processed
    # The ID of the current step from 'current_plan' that is being processed, 
    # potentially by a subgraph. Can be None initially.
    current_main_plan_step_id: Optional[str]


# --- Research Team Subgraph Specific State Definitions ---

class SubTask(BaseModel):
    """
    Represents a single, actionable sub-task identified by the router node 
    within the Research Team subgraph. Each sub-task is designed to be 
    executed by a specific type of researcher.
    """
    sub_task_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="A unique identifier for this sub-task, e.g., generated by the router."
    )
    description: str = Field(
        description="A detailed textual description of what needs to be accomplished for this sub-task. This includes specific instructions and requirements "
                    "for the assigned researcher. "
    )
    assigned_researcher_type: str = Field(
        description="Specifies the type or role of the researcher designated to perform this sub-task (e.g., 'web_search_researcher', "
                    "'patent_analysis_researcher', 'coding_researcher'). This will be used for routing to the correct specialist node. "
    )
    input_data: Optional[Any] = Field(
        default=None,
        description="Specific input data, parameters, or context required exclusively for this sub-task. This can be derived from the main task objective or "
                    "results of preceding sub-tasks. "
    )
    result: Optional[Any] = Field(
        default=None,
        description="The outcome, data, or findings generated from executing this sub-task. This field is populated by the researcher node upon completion of "
                    "the sub-task. "
    )
    status: str = Field(
        default="pending",
        description="The current execution status of the sub-task (e.g., 'pending', 'in_progress', 'completed', 'failed')."
    )


class TaskPlan(BaseModel):
    """
    Represents a plan for a series of sub-tasks.
    """
    sub_tasks: List[SubTask]


class SummaryOutput(BaseModel):
    """
    Represents the final summary output of a research team subgraph.
    """
    summary: str = Field(description="A detailed summary consolidating all subtask findings")
    completed: bool = Field(description="Set to true if the main task objective has been sufficiently addressed, false otherwise")
    feedback: str = Field(description="If the task is not completed, this field contains feedback on what is missing or needs to be improved")


class ResearchTeamSubgraphState(MessagesState):
    """
    Manages the state for the Research Team subgraph. 
    
    This subgraph is responsible for taking a single, complex research step from the main 
    plan (the 'task_description'), breaking it down into a series of more granular 
    'SubTask' items, orchestrating their execution by appropriate specialized researchers, 
    and then consolidating the results into a final summary for that main step.

    Note: Default values for fields must be handled during state initialization 
    or by the logic within graph nodes.
    """
    # The high-level task description or objective for the current research step, 
    # received from the main graph's planner.
    task_description: str
    
    # A list of 'Observation' objects from the parent main graph, 
    # providing broader context to the subgraph's router node. Initializes to an empty list.
    task_context: Optional[List[Observation]] 
    
    # A list of 'Observation' objects for the current research step.
    observations: List[Observation]

    # An ordered list of 'SubTask' objects. This plan is generated by the 
    # router node within this subgraph. Can be None initially.
    task_plan: Optional[List[SubTask]]
    
    # The zero-based index pointing to the current 'SubTask' in the 
    # 'task_plan' list. Initializes to 0.
    current_sub_task_index: int

    # feedback for summary
    feedback: str
    
    # A comprehensive textual summary that consolidates the results from all 
    # executed 'SubTask' items. This summary directly addresses the 
    # 'task_description'. Can be None initially.
    task_summary: Optional[str]
    
    # A log for recording any errors encountered during the execution of sub-tasks. 
    # Initializes to an empty list.
    error_log: List[Dict[str, Any]]
